import './globals.css';
import React from 'react';

export const metadata = {
  title: 'Idea PRDs & Landing Pages',
  description: 'Auto-generated PRDs and landing pages from Ideabrowser ideas.'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="container">
          <h1>Idea Browser PRDs</h1>
          <p className="muted">Auto-generated from Ideabrowser ideas</p>
        </header>
        <main className="container">{children}</main>
        <footer className="container muted" style={{ marginTop: '4rem' }}>
          <p>Generated by Agentic Builder</p>
        </footer>
      </body>
    </html>
  );
}
